### ISSUE TITLE
Maybe  the tdm measuring process measure the wrong part of ELF?

### ISSUE THREAD

**Issue by Unik-lif** [HyperEnclave/hyperenclave-driver#1]
Hello!
I am A little confused about the ELF format here. In `Hyperenclave` repo, we got the ELF section like below. It seems that when the rust-monitor is compiled, it will have 6 sections and this number will be recorded in `ph_num` of elf header.
```lds
ENTRY(arch_entry)

BASE_ADDRESS = 0xffffff0000000000;

SECTIONS
{
	. = BASE_ADDRESS;

	.header		: {
		__header_start = .;
		KEEP(*(.header))
	}

	. = ALIGN(4K);
	.bss		: { *(.bss .bss.*) *(COMMON) }

	. = ALIGN(16);
	.text		: { *(.text .text.*) }

	. = ALIGN(16);
	.rodata		: { *(.rodata .rodata.*) }

	. = ALIGN(16);
	.data		: { *(.data .data.*) }

	. = ALIGN(4K);
	.got		: { *(.got .got.*) }

	. = ALIGN(4K);
	__core_end = .;

	__entry_offset = arch_entry - BASE_ADDRESS;
	__core_size = __core_end - BASE_ADDRESS;

	/DISCARD/ : { *(.comment) *(.gnu*) *(.note*) *(.eh_frame*) }
}
```
However, in function `load_elf_and_parse_tdm_info` in file `elf.c`, the way we analyse the elf section is like below.
```C
bool load_elf_and_parse_tdm_info(u8 *dst, const u8 *src, u64 phys,
				 unsigned long sme_flags)
{
        // ------------------------
	struct memory_region ph_mem[NR_PH] = { 0 };

	for (i = 0, off = elf.phoff; i < elf.phnum; i++, off += sizeof(ph)) {
       // -------------------------
	}
       	/*
	 * Get the tdm measurement content: hypervisor TEXT and RODATA. TEXT and
	 * RODATA segments are adjacent, to simplify, regard them as one segment,
	 * that is, the measure range is [PH_TEXT.start, PH_RODATA.end].
	 */
	if (!ph_mem[PH_TEXT].size || !ph_mem[PH_RODATA].size) {
		he_warn("text size: %llx. rodata size: %llx\n",
			ph_mem[PH_TEXT].size, ph_mem[PH_RODATA].size);
	}
	hv_mem.virt_start = ph_mem[PH_TEXT].virt_start;
	hv_mem.size = ph_mem[PH_RODATA].virt_start + ph_mem[PH_RODATA].size -
		      ph_mem[PH_TEXT].virt_start;
	hv_mem.phys_start = (hv_mem.virt_start - (u64)dst + phys) | sme_flags;
	tdm.ops->set_tdm_info(&hv_mem);

	return true;
}
```
The `NR_PH` seems to be 5. As shown in the line below in `elf.h`. However, we have 6 sections of ph to load, I've tested and find the elf.phnum is exactly 6 and the NR_PH is exactly 5, therefore the for loop here will iterate for 6 times, accessing memory that we might not taken into consideration in the last loop.

Maybe the `ph_type` should be changed like below? If not, what we want to measure will in fact be BSS section and TEXT section, instead of TEXT and RODATA section. NR_PH is not a program header, but simply a variable that has the default value of 6.
```C
enum ph_type { PH_HEADER, PH_BSS, PH_TEXT, PH_RODATA, PH_DATA_GOT, PH_GOT, NR_PH };
```
Looking forward to your reply.

**Comment by Bonjourz** [comment]
Hi @Unik-lif 

This repository has been archived, and moved to a new location: https://github.com/asterinas/hyperenclave-driver.

If you still have such issue, please copy it there: https://github.com/asterinas/hyperenclave-driver/issues and discuss there.
